language: python
python:
  - "2.7"

# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
script: python -m unittest discover -v $PRODROOT/unittest/src/python/ecomap

# safelist
branches:
  only:
    - dev
