language: python
python:
  - "2.7"

# command to install dependencies
install: "pip install -r requirements.txt"

before_install:
- python -v
- ~/virtualenv/python2.7/bin/python -v

# command to run tests
script: python -m unittest discover -v ecomap/unittest/src/python/ecomap

# safelist
branches:
  only:
    - dev
