language: python
python:
  - "2.7"

before_install:
  - pwd
  - ls ecomap/unittest/src/python/ecomap

# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
script: python -m unittest discover -v ecomap/unittest/src/python/ecomap
