version: 0.0
os: linux
files:
  - source: /ecomap
    destination: /var/www/ecomap
permissions:
  - object: /var/www/ecomap
    owner: www-data
    group: www-data
    mode: 770
hooks:
  ApplicationStop:
    - location: scripts/01-application_stop.sh
    - location: scripts/02-application_stop.sh
    - location: scripts/03-application_stop.sh
      timeout: 100
      runas: root
  BeforeInstall:
    - location: scripts/01-before_install.sh
    - location: scripts/02-before_install.sh
      timeout: 100
      runas: root
  AfterInstall:
    - location: scripts/01-after_install.sh
    - location: scripts/02-after_install.sh
      timeout: 100
      runas: root
  ApplicationStart:
    - location: scripts/01-application_start.sh
    - location: scripts/02-application_start.sh
      timeout: 100
      runas: root
