version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 100
      runas: root
  BeforeInstall:
    - location: scripts/configure_database
      timeout: 100
      runas: root
