version: 0.0
os: linux
files:
  - source: /index.html
    destination: /home/ubuntu/
hooks:
  BeforeInstall:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
